### ISSUE TITLE
Add Blockstore version command

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstore#134]
Would be nice to be able to check the Blockstore version via command line for those developers who have installed Blockstore and are coming back to GitHub to see if they have the latest version installed.

**Comment by jcnelson** [comment]
Added in my tree; will push once the rest of my fixes are ready.

**Comment by jcnelson** [comment]
Added as of 6be8d1f5a7bef605de8d92718b76ce7988b27ccf

**Comment by jcnelson** [comment]
Forgot--we want an RPC call as well.

**Comment by jcnelson** [comment]
Will fold into the `getinfo` RPC call.

**Comment by jcnelson** [comment]
Added
