### ISSUE TITLE
suggested feature: prompt users installing blockstore for contact info

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstore#135]
If nodes could each be associated with contact information, then they could be contacted by developers and community members who would like to suggest an upgrade, especially in the instance of a critical upgrade.

Email addresses could be used here, or some other method of contact.

Such associations would be optional, in order to protect the privacy of those running nodes. In addition, one could create burner email addresses and still be able to receive messages from others.

This would greatly bolster the abilities of the community to push upgrades.

**Comment by jcnelson** [comment]
Dup of #116

**Comment by shea256** [comment]
:+1:
