### ISSUE TITLE
suggested feature: add an alert system that warns of critical issues in the output logs

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstore#136]
This could function similar to the one in Bitcoin Core.

More information here: https://bitcoin.org/en/developer-reference#alert

> The alert message warns nodes of problems that may affect them or the rest of the network. Each alert message is signed using a key controlled by respected community members, mostly Bitcoin Core developers.
>
> To ensure all nodes can validate and forward alert messages, encapsulation is used. Developers create an alert using the data structure appropriate for the versions of the software they want to notify; then they serialize that data and sign it. The serialized data and its signature make up the outer alert message—allowing nodes which don’t understand the data structure to validate the signature and relay the alert to nodes which do understand it. The nodes which actually need the message can decode the serialized data to access the inner alert message.
>
> ...
>
> Alert key compromise: Bitcoin Core’s source code defines a particular set of alert parameters that can be used to notify users that the alert signing key has been compromised and that they should upgrade to get a new alert public key. Once a signed alert containing those parameters has been received, no other alerts can cancel or override it. See the ProcessAlert() function in the Bitcoin Core alert.cpp source code for the parameters of this message.

**Comment by jcnelson** [comment]
Dup of #115

**Comment by shea256** [comment]
:+1:
