### ISSUE TITLE
Update Contributors page to show "Blockchain ID"

### ISSUE THREAD

**Issue by john-light** [blockstack/blockstore#145]
Update "Passcard" on Contributors page to "Blockchain ID"

https://github.com/blockstack/blockstore/wiki/Contributors

![passcardcontributor](https://cloud.githubusercontent.com/assets/9424721/10175905/77509d92-66a6-11e5-9a46-b6a8a8305caf.png)

**Comment by muneeb-ali** [comment]
Done.
