### ISSUE TITLE
decide on the mechanics for issuing name renewals

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstore#15]
Two options:

A. make "name renewal" a separate operation from name registration

Pros: it's more explicit, and it encapsulates the functionality better. Also, if we add "admin" functionality, we can allow admins to renew names.
Cons: one extra call to worry about.

B. interpret a name renewal as a name registration on an already registered name (given that the owners match up and the operation is considered valid)

Pros: the end user has to worry about less calls.
Cons: if we add support for name "admins", it's unclear how we would allow admins to renew names on behalf of users.

**Comment by jcnelson** [comment]
We went with A.
