### ISSUE TITLE
Fast bootstrapping

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstore#154]
Make it so Blockstore can bootstrap itself from another Blockstore node's database, given a known-good consensus hash.

* Make Blockstore keep the history of each name operation.
* Make it so Blockstore can get the set of operations processed at block K, so it can generate the consensus hash for block K+1 independently.

**Comment by ericwooley** [comment]
Any progress on this? Getting started is painful!

**Comment by jcnelson** [comment]
Yes, this works in my patchset.  Turned out to be somewhat complicated to design a database that could restore itself to any prior point in time, while being space efficient :/

Will push out the code soon.

**Comment by jcnelson** [comment]
Added

**Comment by ericwooley** [comment]
@jcnelson Any docs on this?

**Comment by jcnelson** [comment]
We're going to do a "doc-a-thon" on Friday, but I'll give you the short version here.

Suppose you have downloaded a copy of an untrusted blockstore database at `/tmp/untrusted.db`, but you know for a fact that the consensus hash at block 383000 is supposed to be `93c2718ebd7544a86c3a13ad477789c9`.  Using this knowledge, you can have blockstore verify that `/tmp/untrusted.db` was generated with all the name operations from the blockchain (up to block 383000) using the following command:

```
$ blockstored verifydb 383000 93c2718ebd7544a86c3a13ad477789c9 /tmp/untrusted.db
```

If it succeeds, then you know `/tmp/untrusted.db` can be trusted, since it could only have been generated using the exact sequence of name operations encoded in the blockchain.
