### ISSUE TITLE
wiki suggestion: requirement of python-dev package for Debian 8

### ISSUE THREAD

**Issue by justinguy** [blockstack/blockstore#162]
On a clean Debian 8 (Jessie) the pip install will fail unless you have the Python Development Headers installed. Didn't test on Ubuntu but probably the same. The error given would be misleading to most developers:

![screenshot 2015-10-21 at 18 55 42](https://cloud.githubusercontent.com/assets/14916111/10657335/6f226e80-7825-11e5-8531-a7b7665d7ee5.png)

Fixed with: `apt-get install python-dev`

**Comment by jcnelson** [comment]
Hi @justinguy,

Thanks for pointing this out.  Just added it to the Usage section.
