### ISSUE TITLE
Exception with testset conflict in blockstore.ini

### ISSUE THREAD

**Issue by justinguy** [blockstack/blockstore#163]
Fresh Debian Jessie installation with blockstore 0.0.6 installed with `pip`. `blockstore.ini` created is:

```
[bitcoind]
passwd = opennamesystem
server = btcd.onename.com
port = 8332
use_https = True
user = openname

[blockcypher]
api_token = w

[dht]
disable = True
port = 6265
servers = dht.blockstack.org:6265,dht.onename.com:6265,dht.halfmoonlabs.com:6265,127.0.0.1:6265

[blockstore]
testset = False
max_subsidy = 0
```

From that point on any calls to `blockstored` such as `blockstored stop` or `blockstored start` produce the error:

```
Exception: Blockstore configured to run with testset=True, but given testset=False via command-line
```

Work around I found was to remove `[blockstore]` section from `blockstore.ini`, then daemon can be started or stopped without trouble (and it starts with testset = False as expected).

**Comment by jcnelson** [comment]
Hey @justinguy,

Thank you for your report.  This should be fixed in my next round of patches.

**Comment by justinguy** [comment]
Thanks @jcnelson. I actually just submitted pull request #165 that fixes this, was pretty simple and similar to the fixed https issue #148 (casting to `bool`)

**Comment by jcnelson** [comment]
This should be fixed now.  You only need to pass `--testset` to blockstored.  No `testset` directive is needed in the config file.

**Comment by justinguy** [comment]
Thanks @jcnelson. I just closed the pull request I had to fix it.
