### ISSUE TITLE
Make UNIX script for auto installing blockstored on Debian

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstore#168]

**Comment by ericwooley** [comment]
I just wrote one here https://github.com/blockstack/blockstore/issues/167#issuecomment-152335125

**Comment by muneeb-ali** [comment]
Awesome! Want to put it in 

> images/scripts/debian.sh 

and send a pull request? 

I'm thinking of keeping any platform-specific scripts etc in that folder along with info on docker images etc.
