### ISSUE TITLE
discussion for names for rpc calls

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstore#18]
Starting with DHT calls, options are:

1) For storing data to DHT dht_store, dht_put, something without "dht_" ? This call will take a <value> and return True/False and a <hash> e.g., 
```
dht_store <value> 
```
2) For reading data from DHT dht_read, dht_get, something without "dht_"> This call will take a <hash> and return <value> or None e.g.,
```
dht_get <hash>
```

**Comment by taoeffect** [comment]
@muneeb-ali
> a) Make them exactly the same (cli remains 'thin' and most of the processing happens at opennamed)

@shea256
> Yeah, I like the first option (keeping them the same and keeping the cli thin)

Thanks! It makes the lives of third-parties easier too. :smile: :+1:

**Comment by shea256** [comment]
Awesome! Closing this if there are no objections.
