### ISSUE TITLE
show correct version of blockstore in getinfo RPC call

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstore#195]
We should track the version only in config.py and use that in setup.py and display it in getinfo RPC call. 

Right now, I was just bumping up version numbers directly in setup.py

**Comment by jcnelson** [comment]
Should be fixed as of 2a4568f98338adf1da5ba804420f166bb61fd583

**Comment by muneeb-ali** [comment]
Duplicate of #204
