### ISSUE TITLE
Keep releases consistent with latest version

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstore#200]
We're currently using the master branch as "testing" and not stable. The latest "stable" should be available from releases and kept consistent with PyPi

https://github.com/blockstack/blockstore/releases

**Comment by muneeb-ali** [comment]
New process: create a new 'staging' branch and keep latest code there. Master always has latest release.

**Comment by gcsolaroli** [comment]
May I suggest to look into git-flow?
- http://nvie.com/posts/a-successful-git-branching-model/

It is already supported also by different tools.

**Comment by muneeb-ali** [comment]
Great link! We were moving to a somewhat similar model independently. Can move to this instead, so that we can refer people to the appropriate doc that contains a detailed explanation of the branching model.

**Comment by muneeb-ali** [comment]
Found: https://github.com/nvie/gitflow

Are there any other tools you recommend?

**Comment by gcsolaroli** [comment]
I am using Tower [1], and git-flow is integrated right inside the app.
I have also used a maven plugin that would do releases following git-flow layout.
Otherwise, I have not used other tools, so I can not really help; sorry.

[1]: http://www.git-tower.com

**Comment by muneeb-ali** [comment]
We started using the git flow model for development. Closing this issue.

**Comment by muneeb-ali** [comment]
thanks @gcsolaroli for your input on this!
