### ISSUE TITLE
reducing data requirements and network costs of name operations

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstore#34]
Here, I'm proposing an alternative way of executing and interpreting name operations...
with the purpose of reducing data requirements and network costs.

(not: just a proposal - not sure if this is the way to go, since it definitely has drawbacks)

Right now, we embed the operation instructions directly in the OP_RETURN data. That is, the data contains a code for the operation, and then the parameters for that operation. For example, if it's a name update, we specify it's an update, then we include the name that's being updated, and then we include the hash of the data to be associated with the name.

Advantages:

+ all you need to read and interpret the sequence of operations is the sequence of relevant OP_RETURN nulldata embedded directly in the blockchain
+ to get a basic view of the namespace, you don't need to pull data from outside sources, like DHTs or APIs

Disadvantages:

+ data embedded in the blockchain scales with the number of operations
+ if the data associated with a name needs to be updated frequently, the network costs can get super high

New method:

Instead of including the operation instructions directly in the OP_RETURN nulldata...

You format the operation, then sign it with the private key of the owner, then hash it and include that hash in the blockchain, making sure the operation itself is available in a DHT.

If you want to include 10 operations for 10 different names owned by 10 different private keys, you can create the 10 signed operations, bundle them together, then hash and include the bundle in the blockchain, and serve the bundle from a DHT

Advantages:

+ cheaper
+ lower data requirements
+ lets you do thousands of updates with a single bitcoin transaction

Disadvantages:

+ a single bit of data being unavailable means that the whole view can't be built
+ requires more work for nodes - they have to do more DHT lookups
+ less elegant
+ probably something else I haven't thought of

**Comment by jcnelson** [comment]
We have implemented (1) already, and (2) can be had if we put all profile data into mutable storage.

**Comment by shea256** [comment]
What do you mean by we've implemented method (1) already? Do you mean we've already implemented a "one tx, one name registration" operation?

And for 2, this isn't really pertaining to mutable data, wouldn't you say? I'm talking about hash-packing so that we can have an unlimited number of immutable data updates in a single transaction. One big merkle tree or merkle dag of operations.
