### ISSUE TITLE
consider removing salt from name preordering and registration

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstore#37]
Currently the preorder hash is calculated as follows: `hash(name + salt + scriptPubKey)`

Matt Corallo points out that `hash(name + scriptPubKey)` is equivalent if the scriptPubKey has never been used before.

This would simplify things AND would save us a bunch of space in the name registration transaction (about 16 bytes, I believe).

The only thing we'd have to do is make it clear that people shouldn't reuse pubkeys (they shouldn't be doing so anyway) unless they want to risk that someone will try to dictionary attack them.

**Comment by jcnelson** [comment]
This has been addressed by requiring a `preorder` operation to use the address of an as-of-yet-unused key pair as the salt.  The address will be revealed in the `register` operation, and used as the name's owning address.  Any subsequent operations on the name must be sent from this address.

**Comment by shea256** [comment]
:+1:
