### ISSUE TITLE
Dev/Demo/Debug/Mock mode that doesn't require bitcoind

### ISSUE THREAD

**Issue by taoeffect** [blockstack/blockstore#64]
Would help greatly if you could add like a `--demo` or `--mock` flag to just run the json rpc server with some dummy data that can sent/retrieved. This mode would bypass the requirement for a `bitcoind` server.

As a simple first start, just some dummy data (that's properly formatted) for the `lookup` rpc command would help.

Not super high priority of course, but if it's easy to do and you can do it quick we can add support for blockstore to DNSChain 0.5.0 this weekend. Otherwise it'll make it into the next release.

**Comment by shea256** [comment]
This is a good idea. We can look into this. And when is the next DNSChain release?

**Comment by taoeffect** [comment]
> And when is the next DNSChain release?

DNSChain is pretty stable right now and so we're focusing on a crowd fund. Given there are no burning fires, we could focus on Blockstore for the next release, provided there's a TLD of some sort and good docs on the matter.

**Comment by shea256** [comment]
Gotcha, thanks!

**Comment by jcnelson** [comment]
This is a good idea, especially for CI and unit tests.  I'll add it.

However, you might be interested to know that we already support using Bitcoin testnet, and we also have a "testset" mode that lets you do all the same things you would in Blockstore, but in a way that won't be picked up by Blockstore, and won't cost a lot of BTC (you just pay the dust fees and mining fees).

**Comment by shea256** [comment]
I think this would be huge. This would enable automated testing and build statuses, as we could run hundreds of tests in seconds with this.

Of course there's no substitute for testing live, but this wouldn't be meant to displace those tests - simply to provide another layer of testing.

**Comment by jcnelson** [comment]
You should be able to set the mock UTXO provider and mock bitcoind from our test framework when running blockstore.

**Comment by jcnelson** [comment]
Added; we use it in our test framework.
