### ISSUE TITLE
Warn users that all their credentials are being exposed in ~/.blockstore

### ISSUE THREAD

**Issue by taoeffect** [blockstack/blockstore#65]
Users should definitely be informed that their Chain API keys (including the secret key) as well as their bitcoind username/password are being stored in plaintext in `~/.blockstore/blockstore.ini`.

**Comment by muneeb-ali** [comment]
Yes, agreed. This should be conveyed. 

Do you have any recommendation for how else can these be stored? Env variables are more secure but then they'll need to reset them in a new shell session

**Comment by taoeffect** [comment]
> Do you have any recommendation for how else can these be stored? Env variables are more secure but then they'll need to reset them in a new shell session 

Well, I would've suggested encrypting them, except the bitcoin credentials are also stored in plaintext by bitcoin itself...

Your best bet would really be to just:

1. Set perms 600 on `blockstore.ini` (`rw-------`).
2. Put a warning message during `blockstartd start` setup

It's unfortunately common practice to store database passwords in plaintext on servers. Sysadmins rely on UNIX perms and app security to protect them. Sometimes the more diligent ones will use full disk encryption (or something like encfs) to attempt to protect them.

**Comment by muneeb-ali** [comment]
Perms to 600 is a no-brainer (thanks for pointing it out!). For the warning, I'm thinking that we can display it as soon as the write to .ini file completes.

**Comment by shea256** [comment]
OK just marked this as a chore that we can take care of.

**Comment by jcnelson** [comment]
Fixed.
