### ISSUE TITLE
blockstore-cli preorder error

### ISSUE THREAD

**Issue by bypassfuture** [blockstack/blockstore#67]
hey guys,

when i  run ** blockstore-cli preorder XXX privkey ** , terminal shows : 

{
    "error": "UnboundLocalError: local variable 'secret_exponent' referenced before assignment",
    "traceback": [
        "Traceback (most recent call last):",
        "  File \"/usr/local/lib/python2.7/dist-packages/blockstore/blockstored.py\", line 253, in jsonrpc_preorder",
        "    blockchain_client=blockchain_client, testset=True)",
        "  File \"/usr/local/lib/python2.7/dist-packages/blockstore/lib/operations/preorder.py\", line 28, in broadcast",
        "    hash160 = BitcoinPrivateKey(private_key).public_key().hash160()",
        "  File \"/usr/local/lib/python2.7/dist-packages/coinkit/privatekey.py\", line 61, in __init__",
        "    if not is_secret_exponent(secret_exponent, self._curve.order):",
        "UnboundLocalError: local variable 'secret_exponent' referenced before assignment"
    ]
}

what's wrong ? 
thanks ;)

**Comment by shea256** [comment]
Hm, I believe there is a problem with the coinkit library when you use a private key that is incorrectly formatted.

Can you check to make sure you're using a valid private key?

I'll submit a patch to coinkit to make sure this error gets properly catched in the future.

**Comment by shea256** [comment]
@bypassfuture any update on this? Did you figure this out?

**Comment by bypassfuture** [comment]
Hey , Yes !  i use compressed and uncompressed format both .  It still shows the same :(

**Comment by jcnelson** [comment]
@bypassfuture The code that handles the private key loading has been re-worked to support both compressed and uncompressed format.  I think I was able to reproduce your problem.  At your convenience, can you confirm that the problem has been removed from the 'jude' branch?

**Comment by jcnelson** [comment]
@bypassfuture This has been fixed in the [jcnelson-master](https://github.com/blockstack/pybitcoin/tree/jcnelson-master) branch of pybitcoin.  Please install the latest version and let us know if it works for you?  Thanks!

**Comment by shea256** [comment]
OK @jcnelson want to hop over to pybitcoin and submit a PR? I'll merge it in and push a new pybitcoin version.
