### ISSUE TITLE
Blockstored exiting after processing block 343887

### ISSUE THREAD

**Issue by satorsq** [blockstack/blockstore#70]
Blockstore team,

New issue today.  Created my own bitcoin node (107.191.41.5:8332) to get around the load balancing issue on btcd.onename.com.  Confirmed that the node had an up to date blockchain.  Installed blockstore with pip and then started up blockstored.  Used a local host address (127.0.0.1) and completed the rest of blockstored's config questions.  

Every time I run this blockstored processes blocks 343883 through 343887 and then exits:

<i>
Creating initial index ...
Processing block 343883
block_nameops []
Processing block 343884
block_nameops []
Processing block 343885
block_nameops []
Processing block 343886
block_nameops []
Processing block 343887
<i>
Exiting blockstored server 

Stumped as to what might be happening.  Anyone experienced this?

Also unable to connect to this specific with blockstored from a non-local instance.  SSL is not enabled on the node.  Is this mandatory?

Happy to privately message you the rpc username and rpc password if you'd like to test functionality.

Thanks again for you attention in this matter as well as your patience with my inexperience.  

Cheers,

Jonathan

**Comment by shea256** [comment]
Not sure what's going on, I'll look into this problem and get back to you.

And you're unable to connect to your local namecoind node with a non-local instance of blockstored?

**Comment by shea256** [comment]
I haven't been able to replicate this. Did you get any output or errors after the processing of block 343887?

**Comment by shea256** [comment]
@satorsq any update on this? Have you been able to resolve the issue?

**Comment by muneeb-ali** [comment]
I was not able to replicate this either. @satorsq can you share your setup details, what OS you're using etc

**Comment by satorsq** [comment]
Odd. Still happening for me.  I am running Ubuntu 14.04 LTS.  Bitcoind
v0.10.

Is there any way to run blockstored with more verbose debugging to the
console?


*Jonathan Silverman*
Partner, Head of Trading
*Sator Square Partners*
79 Madison Ave. | Suite 531 | New York, NY 10016
Office: 917.472.9594
Mobile: 732.757.7624
E-mail: jonathan@satorsq.com

**Comment by muneeb-ali** [comment]
blockstored start --foreground

**Comment by satorsq** [comment]
Cheers. I will give that a try when I am back in front of my machine.

**Comment by jfeldis** [comment]
I saw the exact same issue until I tried a blockchain with a full index.  Try setting txindex=1 in bitcoin.conf.  It will need many hours to reindex

**Comment by jfeldis** [comment]
Bitcoind with txindex=1 - it ran all night processing blocks and then exited about 2500 short of the current block.  no error code.

   block_nameops []
   Processing block 349760

   Exiting blockstored server

**Comment by jcnelson** [comment]
@jfeldis You are correct--the source of this error is that blockstored had been (silently) exiting because the bitcoind peer it was using did not have a full transaction index.  We will update the documentation to state this more explicitly.

**Comment by jcnelson** [comment]
So...I'm going to close this, with the solution being "run your bitcoind with the -txindex option, because blockstore needs to query raw transactions."
