### ISSUE TITLE
add a call that returns all the names currently registered

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstore#73]
The number of names in existence should be manageable for a while. And as the number of names gets too large for this call to manage, this could eventually be paginated, with the option to skip pages.

**Comment by jcnelson** [comment]
The Blockstore state engine already has a `get_all_names()` method; I can hook it into the RPC server.

**Comment by shea256** [comment]
OK cool. This could also be done on a namespace level too. "Get all names for namespace" instead of "get all names".

**Comment by jcnelson** [comment]
Absolutely.  Will implement that as well.

**Comment by jcnelson** [comment]
Added as of 0ca8da0f15dedc0b93496ad2a06f6b6571708117
