### ISSUE TITLE
blockstore-cli error

### ISSUE THREAD

**Issue by cqtenq** [blockstack/blockstore#78]
When I register a key-value pair, first preorder the name, I get a error information.

blockstore-cli preorder swiftonsecurity N876Ywf8bL5JWMPbHvjHP2AaSF1Ap8Wg4qAn9AAiQbmYFWPh2vqe
{
    "error": "UnboundLocalError: local variable 'secret_exponent' referenced before assignment",
    "traceback": [
        "Traceback (most recent call last):",
        "  File \"/usr/local/lib/python2.7/dist-packages/blockstore/blockstored.py\", line 253, in jsonrpc_preorder",
        "    blockchain_client=blockchain_client, testset=True)",
        "  File \"/usr/local/lib/python2.7/dist-packages/blockstore/lib/operations/preorder.py\", line 28, in broadcast",
        "    hash160 = BitcoinPrivateKey(private_key).public_key().hash160()",
        "  File \"/usr/local/lib/python2.7/dist-packages/coinkit/privatekey.py\", line 61, in __init__",
        "    if not is_secret_exponent(secret_exponent, self._curve.order):",
        "UnboundLocalError: local variable 'secret_exponent' referenced before assignment"
    ]
}

**Comment by jcnelson** [comment]
This is a duplicate of #80.  Closing this issue; please re-open if you encounter it again.
