### ISSUE TITLE
BitTorrent implementation?

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstore#89]
The purpose of building blockstore is to give us higher storage bandwidth and lower storage latency than the blockchain, while preserving the same data authenticity, integrity, and consistency guarantees it offers.  That is, a reader can verify that any record came from the user that claims to have written it under the same threat model as the blockchain, and the reader is guaranteed to observe writes to a record in the same order in which they were accepted by the storage system (i.e. per-key sequential consistency).

Blockstore can guarantee authenticity and integrity by binding a username to a public key hash in the blockchain, and require each record written to include both the username and the user's private key signature over the record.  If we additionally assume that the writer's clock source is monotonically increasing (which is reasonable, easy to implement, and easy for blockstore to verify), we can guarantee consistency by requiring the writer to incorporate the clock's timestamp in the record as well, thereby providing a total ordering of all writes to a particular (key, value) pair.

None of the above *requires* us to implement blockstore as a DHT.  What we want is a highly available and highly durable data store that makes the same security and consistency guarantees as the blockchain while keeping the blockchain off the critical I/O paths.  A DHT whose nodes make the aforementioned checks is only one such implementation.

What we are considering is using a modified BitTorrent swarm instead.  A writer would seed and announce well-formed records from local storage, and interested readers would fetch and re-seed them.  Peers would run a modified BitTorrent tracker (itself a DHT) that additionally ensured that writers could only announce well-formed records--that is, the "announce" message would incorporate not only the chunk hashes and IP addresses, but also the timestamp of the record and a signature over the "announce" message.  Peers would reject announce messages for stale, unauthentic, or corrupt data.  Chunk transfer would occur via the vanilla BitTorrent protocol, and readers would cross-check the announced timestamp and hashes with the record (once assembled).

There are several advantages with using BitTorrent in this way:
* **High Availability for Hot Content:**  By having readers re-seed reads, popular data gets widely replicated and becomes highly available and durable.
* **Control the "Long Tail" of Availability:** Because the user seeds new data itself, it is free to replicate it however it wants.  For example, a writer could place seeders for its data in EC2 for higher guaranteed durability and availability.  This could be further addressed by highly-available backend storage like [Syndicate](https://github.com/jcnelson/syndicate) or [ipfs](http://ipfs.io/).  We could also seed data as a service to users.
* **Availability behind NATs:**  We want as many people as possible to run peers to increase blockstore's availability, but users are often behind NATs.  However, there are widely-used BitTorrent libraries (i.e. libtorrent) that can automatically traverse NATs that are available today.  This would save us the effort of having to address this independently for blockstore's Kademila implementation.
* **Resiliency to Partitions:** Previously-read data will be available locally (possibly up to a maximum age), so they can work offline or with spotty network conditions.  Moreover, for popular content, it is unlikely that all peers that can serve a particular chunk will be offline.
* **Resiliency to Churn:**  The data only needs to be available from one peer in order for readers to make forward progress.  The writer and readers for a record can come and go otherwise.
* **Immunity to Sybils:** Our integrity, authenticity, and consistency guarantees ensure that the worst a Sybil can do is degrade (but not deny) service.  A Sybil node cannot seed arbitrary data, since peers will detect signature mismatches.  It cannot serve well-formed but stale records, since readers will detect conflicting versions from non-Sybil peers and accept the latest version.
* **Fairness:**  We can take advantage of the network-level and chunk-level fairness algorithms that have evolved over the past 14 years to incentivize peer cooperation (i.e. "you leech? you lose bandwidth").  We don't have to reinvent this wheel for Kademila.
* **Familiarity to Users:** Even mildly-tech-savvy users know what BitTorrent is.  DHTs much less so.

I'm opening this issue to get a discussion going on the pros and cons of using BitTorrent in this manner.  Are the above guarantees things that we want to offer?  Are there better ways to make these guarantees?  What are some drawbacks of BitTorrent?

**Comment by muneeb-ali** [comment]
Thanks for the suggestion, @jcnelson! Looping in @jbenet and @bmuller 

I like the approach of using already deployed infrastructure, instead of putting a lot of effort into a specialized DHT for Blockstore. It'll be good to have a comparison of BitTorrent approach vs current Kademlia based DHT i.e., some of the benefits listed are possible with the current implementation as well e.g., immunity to Sybils. 

If we're going ahead with this, are there any particular implementations that we'll use? Having a quick look at potential implementations can also narrow down benefits of current approach vs. this i.e., what functionality is already available and what things we'll need to implement.

**Comment by jbenet** [comment]
@jcnelson @muneeb-ali IPFS handles all of those points, it gives you a programmable interface much more sophisticated than bittorrent, and separates into a clean stack of protocols so you can use what you need or replace pieces. It sounds like you guys haven't played with IPFS deeply yet-- I happen to be in NYC today through thursday. Happy to stop by your office and give you a hands-on high-throughput demo. I think fast Q/A is the best way to get synced up here.

**Comment by bmuller** [comment]
I think this is an idea definitely worth exploring.  To be clear, though - a few of the "advantages" listed are not advantages of BitTorrent over just a DHT (High Availability for Hot Content for instance is something you get with Kademlia as well as access behind a NAT).  

Some of the advantages listed don't seem like they would naturally arise either - but it could just be that I'm missing some part of the proposed design.  Much of the benefit of BitTorrent, comes from many peers having copies of content you want.  I don't see many peers having a need to see most of the user data in the storage - so I'm not sure about most of the gains listed and if they apply if only one or two seeders exist for data (for instance, if all I do is log into Google and Facebook because they use data in the blockstore for auth, why would any other service/peer/whoever ever download my data from the blockstore and act as seeds as well).

**Comment by muneeb-ali** [comment]
@jbenet Dropped you an email re chatting at our office. 

@bmuller: Agreed, that some of the benefits are coming from just a DHT. In fact, for the hot content can do "structured replication" like [Beehive](https://www.cs.cornell.edu/people/egs/beehive/) (implemented on top of Kademlia routing). 

BTW, we're dividing data into two categories now. Your basic profile (mostly has your PGP / RSA pub keys) and "extended profile" (rest of your data). We're mostly talking about storing the basic profile, so the amount of data is going to be small. 

See your point about why other peers would download/seed this data. Somewhat similar problem to incentivizing people to join the current DHT system. With BitTorrent they have incentive to join the system, just not to download/host your data. Let me think more about this.

**Comment by jcnelson** [comment]
@muneeb-ali I was anticipating that down the road, people would build applications that host their data with blockstore (in addition to user public keys).  This is what got me thinking about availability and durability in the face of uneven read-heavy load distributions common to Web applications.

@bmuller I had put "high availability for hot content" as an advantage of BitTorrent in this particular application because readers would seed their reads by design.  While a particular Kademlia implementation can do things like cache values from prior get-requests, employ consistent hashing to reduce the effects of churn on availability (while increasing durability), and employ additional replication strategies (like Beehive) on top of the system, I had considered these as implementation-level details that weren't specific to Kademlia.  But, is there something intrinsic to Kademlia's design that makes it amenable to handling hot content?  I'd love to know for my own edification :)

**Comment by bmuller** [comment]
@jcnelson From the paper - "For caching purposes, once a lookup succeeds, the requesting node stores the (key, value) pair at the closest node it observed to the key that did not return the value."  As more requests for the same key are made, more nodes will store the value.  This results in high availability for hot content.

**Comment by shea256** [comment]
Looping in @jmonegro as well. He suggested this a few months back and we investigated it a bit and thought it was promising but ultimately decided on Kademlia. Definitely think this is worth a re-consideration.

**Comment by LysanderAkili** [comment]
This is exactly what I am aiming for. 

Law firms would provide their own seedbox, and seed to the masses. It could also include a fee for creating a new ID.  I personally think this is a better approach.

**Comment by LysanderAkili** [comment]
Also, It could use a zmap, or yacity as a decentralized search engine. It searches for other magnets/torrents in the network, and lists them on your end.

**Comment by muneeb-ali** [comment]
I think @jcnelson point about "cache values from prior get-requests" is pretty much what @bmuller is pointing out as well. As for if this is a particular implementation detail or part of the core Kademlia design, I've always considered Kademlia as just the routing table + lookup. From the paper it seems that they describe caching as a part of the lookup operation although I always thought of caching as a separate performance improvement. Maybe @petar can comment on how he originally thought about caching. 

I'd love to see a discussion about understanding the core benefits and/or tradeoffs of continuing down our current path i.e., the Python Kademlia implementation by @bmuller + making modifications to policy on what can be stored in the DHT, what type of writes do we accept, and who can join the network (basically using the blockchain transactions or proof of ownership of bitcoins to limit Sybil attacks) vs. starting a BitTorrent based implementation.

**Comment by jcnelson** [comment]
Wrapping up from the Blockstack Summit, the solution we're going with is to provide both the DHT (which spans high-uptime Blockstore peers), as well as DHT mirrors (which anyone can run for any key space).  Application providers would be encouraged to run both DHT nodes and mirrors their users' data to ensure its availability.  Moreover, the [Blockstore client](https://github.com/blockstack/blockstore-client) allows the user to put their data into whatever storage providers the client can talk to, and other clients will automatically fetch and validate them.  This gains all of the features I was considering getting out of using BitTorrent, so I'll close this issue.
