### ISSUE TITLE
replace the "coinkit" dependency with "pybitcoin" in setup.py and requirements.txt

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstore#96]
It looks like @jcnelson made some patches to Coinkit to allow it to support compressed public keys.

It turns out that Pybitcoin, the replacement to Coinkit already has compressed public keys built in.

Maybe we can take a look at Jude's patches and pull anything in to Pybitcoin that is missing.

In any case, after this we should have support for compressed public keys.

**Comment by muneeb-ali** [comment]
Yeah @jcnelson and I discussed this over the weekend that we need to move to using pybitcoin. This patch a quick thing given the Mon deadline and definitely moving to pybitcoin.

**Comment by shea256** [comment]
OK cool.

**Comment by jcnelson** [comment]
This is fixed in my branch.

**Comment by jcnelson** [comment]
Marking this as resolved.  Please re-open if it is still a problem.  Thanks!
