### ISSUE TITLE
Save cache after every block

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstore#98]
Currently, blockstored saves cache after it syncs up with the blockchain. There is no real reason to do this. We can save the cache/state of the namespace after each block that was successfully processed. This way for any errors, we can resume from the last successfully processed block

**Comment by jcnelson** [comment]
This is fixed in my branch.

**Comment by jcnelson** [comment]
Marking this as resolved.  Please re-open if it is still a problem.  Thanks!
